version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

  performance_test:
    docker:
      - image: loadimpact/k6

    working_directory: ~/report

    environment:
      HOST_NAME: another-nodejs-shopping-cart.herokuapp.com

    steps:
      - checkout
      - run: k6 run --vus 10 "tests/smoke-test.js"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - performance_test:
          requires:
            - build
