default: &defaults
  parallelism: 1
  working_directory: ~/repo

k6_performance_tests: &k6_performance_tests
  run:
    name: Running k6 tests

    command: |
      docker pull loadimpact/k6:latest
      docker run -i -v $HOME/repo:/ci/ loadimpact/k6:latest run tests/smoke-test.js

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run: npm install
      - *k6_performance_tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
